---
apiVersion: v1
kind: Service
metadata:
  name: cloudsigma-controller-manager-metrics
  namespace: capcs-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: cluster-api-provider-cloudsigma
    app.kubernetes.io/component: controller
spec:
  selector:
    control-plane: controller-manager
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
