---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudsigma-controller-manager
  namespace: capcs-system
  labels:
    app.kubernetes.io/name: cluster-api-provider-cloudsigma
    app.kubernetes.io/component: controller
